# -*- coding: utf-8 -*-
"""Juego.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLRT67BRYdjzg-hklELUgxdZVUzGKIN9
"""

# app.py
import streamlit as st
import pandas as pd
import random

st.set_page_config(page_title="Juego Antifiestas", layout="centered")

st.title("🎮 Juego Antifiestas")
st.subheader("Evita hoy lo que te hizo gastar antes")

# =============================
# Datos históricos
# =============================
data = {
    "fecha": pd.date_range(start="2024-01-01", end="2024-01-31"),
    "gasto_2024": [
        0,0,0,0,0,2168,0,0,0,0,1908,0,0,1898,0,2258,0,0,0,0,0,0,0,0,1303,0,2008,0,0,0,0
    ],
    "gasto_2025": [
        0,0,0,0,0,0,0,517,0,1354.38,0,0,0,787.72,675.04,0,0,0,0,0,0,0,3600,0,0,804.56,0,0,0,0,0
    ]
}

df = pd.DataFrame(data)

# =============================
# Estado del juego
# =============================
if "dia" not in st.session_state:
    st.session_state.dia = 0
    st.session_state.ahorro = 0.0
    st.session_state.puntos = 0
    st.session_state.historial = []

# =============================
# Fin del juego
# =============================
if st.session_state.dia >= len(df):
    st.success("🏁 Juego terminado")

    st.metric("💰 Ahorro total logrado", f"${st.session_state.ahorro:,.2f}")
    st.metric("⭐ Puntos financieros", st.session_state.puntos)

    st.subheader("📊 Historial de ahorro diario")
    st.bar_chart(st.session_state.historial)

    st.divider()
    st.header("🥠 Galletitas Financieras")

    mensajes = [
        "💡 Ahorra primero, gasta después.",
        "📊 Lleva un registro mensual de tus ingresos y gastos.",
        "💰 Invierte en instrumentos que entiendas.",
        "🧾 Evita las deudas que no generen valor.",
        "🎯 Define metas financieras claras y realistas.",
        "🏦 El interés compuesto premia la paciencia.",
        "💳 El crédito es herramienta, no ingreso.",
        "🪙 Construye tu fondo de emergencia.",
        "📚 La educación financiera paga el mejor interés.",
        "🧘‍♂️ La disciplina vence al impulso."
    ]

    if st.button("🍪 Romper una galletita"):
        st.success(random.choice(mensajes))

    st.stop()

# =============================
# Día actual
# =============================
fila = df.iloc[st.session_state.dia]
fecha = fila["fecha"].strftime("%d-%m-%Y")
gasto = fila["gasto_2024"] + fila["gasto_2025"]

st.header(f"📅 {fecha}")

if gasto > 0:
    st.warning(f"🎉 Tentación detectada\n\nCosto histórico: **${gasto:,.2f}**")

    col1, col2 = st.columns(2)

    with col1:
        if st.button("❌ Evitar fiesta"):
            st.session_state.ahorro += gasto
            st.session_state.puntos += int(gasto / 100)
            st.session_state.historial.append(gasto)
            st.session_state.dia += 1
            st.rerun()

    with col2:
        if st.button("🍻 Ir a la fiesta"):
            st.session_state.historial.append(0)
            st.session_state.dia += 1
            st.rerun()
else:
    st.info("😌 Día tranquilo, sin gastos históricos")
    st.session_state.historial.append(0)
    st.session_state.dia += 1
    st.rerun()

# =============================
# Indicadores
# =============================
st.divider()
st.metric("💰 Ahorro acumulado", f"${st.session_state.ahorro:,.2f}")
st.metric("⭐ Puntos", st.session_state.puntos)

# =============================
# Estilos
# =============================
st.markdown("""
<style>
    .stApp {
        background-color: #f5f7fa;
    }
</style>
""", unsafe_allow_html=True)
